### ISSUE TITLE
How to initialize glimpses with specific coordinates?

### ISSUE THREAD

**Issue by duygusar** [SunnerLi/ram#1]
This is not really an issue with the code, your code is very clear compared to other RAM implementations but I have a question I can not figure out: I would like to customize the starting point of the glimpse network (I compute this based on a heatmap). But the initial location seems to be chosen with the format: init_location = tf.random_uniform((tf.shape(images_ph)[0], 2), minval=-1.0, maxval=1.0). I understand this is a special coordinate input (to extract glimpse) where 0.0 0.0 is the center. How can I pass my specific coordinates? Thanks.

**Comment by SunnerLi** [comment]
Hi @duygusar ,
I'm sorry that I give the response for too long.
Additionally, The last I I wrote TensorFlow is about 10 month ago...
So the answer might not be correct.
However, I also give you my suggestion, and hope it can help you.

```python
# Construct Glimps network (part in core network)
init_location = tf.random_uniform((tf.shape(images_ph)[0], 2), minval=-1.0, maxval=1.0)
init_glimps_tensor = glimps_network(init_location)
```

The above code is the piece in the `main.py`.
After the graph component `init_location` was create, it will be sent into `glimps_network`.
In the `glimps_network`, the `init_location` object will become the input of `self.getGlimps`.
If you want to custom your containing of the tensor,
you should change it as the `tf.placeholder`.
After doing this adjustment, you can feed the specific coordinate what you want.
Hope these suggestion can help you.
